### PR TITLE
show thumnails on map, env for keys, show artist pic

### PR DESCRIPTION
**Pull request by ah1053**
- Show thumbnails on the map (probably needs some artistic touch from you) @studiobloom 
- Move web requests to the `api` directory.
- Show artist profile image.

### CODE REVIEW

**Comment by studiobloom** [comment]
There's a bug with your update on the image markers, when you drag the map the markers stay in place instead of following their location. 

Everything on the API side of things is working great when I run locally.

The conflict for the merge comes from both of us adding changes to AssetView.js as I needed to add the 'linkify' function as per client's request.

**Review by studiobloom — APPROVED** [review]

**Comment by studiobloom** [comment]
Just need a final review from @ah1053 and we're good to merge to main and push live:)

**Comment by studiobloom** [comment]
Tested Linkify locally and all is working.

After attempting to deploy from a clone via netlify, the build fails when running npm run build due to issues with webpack, but builds fine with npm run dev.

**Comment by ah1053** [comment]
Icons look neat on the map @studiobloom Thank you 🚀

**Pull request merged**
